spring:
  profiles:
    active: dev

# Common configurations
---

server:
  port: 8082

spring:
  application:
    name: schedlr-profile-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.AtomikosJtaPlatform
  mail:
    host: smtp.gmail.com
    port: 587
    username: schedlr.noreply@gmail.com
    password: lkeo ewlv fzdd ihel
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Profile-specific configurations
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/schedlr
    username: root
    password: root

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://schedlr-aws.cvu48ycmk8x0.ap-southeast-2.rds.amazonaws.com:3306/schedlr
    username: root
    password: schedlr10